image: gitlab.kwant-project.org:5005/qt/research-docker

before_script:
  - mkdir -p micromamba
  - export MAMBA_ROOT_PREFIX=micromamba
  - micromamba create -yf docs/environment.yml
  - eval "$(micromamba shell hook --shell bash)"
  - micromamba activate pydacp-docs

run docs:
  variables:
    OPENBLAS_NUM_THREADS : 1
    OMP_NUM_THREADS : 1
    MKL_DYNAMIC : FALSE
    MKL_NUM_THREADS : 1
  script:
    - make -C docs/ html SPHINXOPTS="-WT --keep-going -n"
  artifacts:
    paths:
      - docs/build
  cache:
    key: "$CI_JOB_NAME"
    paths:
        - micromamba

run pre-commit:
  variables:
    PRE_COMMIT_HOME: $CI_PROJECT_DIR/.pre-commit-cache
  script:
    - micromamba install -c conda-forge -y mamba pip pre-commit git
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - pre-commit run --all-files
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - .pre-commit-cache
      - micromamba

pages:
  needs:
    - run docs
  script:
    - mkdir public
    - cp -r docs/build public/
  artifacts:
    paths:
      - public
